In [9]:
import numpy as np

In [2]:
myList1 = [1,2,3,4]

In [3]:
myArray1 = np.array(myList1)

In [4]:
print myArray1

[1 2 3 4]


In [5]:
myArray1

array([1, 2, 3, 4])

In [6]:
myList2 = [11,22,33,44]

In [7]:
myLists = [myList1, myList2]

In [8]:
myLists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [3]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [6]:
myZerosArray = np.zeros(5)

In [7]:
myZerosArray.dtype

dtype('float64')

In [14]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [20]:
bool_arr = np.array([True,False,True])

In [21]:
bool_arr

array([ True, False,  True], dtype=bool)

In [23]:
bool_arr.any()

True

In [24]:
bool_arr.all()

False

In [26]:
#Sorting Arrays

arr = randn(5)
arr

NameError: name 'randn' is not defined