In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

from numpy.random import randn

In [2]:
ser1 = Series([1,2,3,4], index = ['A','B','C','D'])
ser1

A    1
B    2
C    3
D    4
dtype: int64

In [3]:
ser2 = ser1.reindex(['A','B','C','D','E','F'])
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [5]:
ser2.reindex(['A','B','C','D','E','F','G'], fill_value = 0)

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
G    0.0
dtype: float64

In [6]:
ser3 = Series(['USA','Mexico', 'Canada'], index=[0,5,10])

In [7]:
ser3

0        USA
5     Mexico
10    Canada
dtype: object

In [9]:
ranger = range(15)
ranger

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [10]:
ser3.reindex(ranger,method = 'ffill')

0        USA
1        USA
2        USA
3        USA
4        USA
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14    Canada
dtype: object

In [24]:
rNums = randn(25)
rNums

rNums = rNums.reshape(5,5)

print rNums


[[-0.9707254  -1.10063449 -1.79652408  0.3514514  -2.19211989]
 [-1.56697655 -0.67569223  0.47293825 -0.28723181 -1.80927442]
 [ 0.71488288 -0.36996519  0.10824528  0.1086384  -1.38771289]
 [ 0.76023252  2.55852222  0.58064297  0.44086514  0.48946744]
 [ 0.13976686 -0.28209381  0.33152217 -0.68431838 -0.29704001]]


In [26]:
dframe = DataFrame(rNums, index = ['A', 'B','D','E','F'], columns = ['col1', 'col2','col3','col4','col5'])

dframe

col1      col2      col3      col4      col5
A -0.970725 -1.100634 -1.796524  0.351451 -2.192120
B -1.566977 -0.675692  0.472938 -0.287232 -1.809274
D  0.714883 -0.369965  0.108245  0.108638 -1.387713
E  0.760233  2.558522  0.580643  0.440865  0.489467
F  0.139767 -0.282094  0.331522 -0.684318 -0.297040

In [27]:
dframe2 = dframe.reindex(['A','B','C','D','E','F'], fill_value =99)

In [28]:
dframe2

col1       col2       col3       col4       col5
A  -0.970725  -1.100634  -1.796524   0.351451  -2.192120
B  -1.566977  -0.675692   0.472938  -0.287232  -1.809274
C  99.000000  99.000000  99.000000  99.000000  99.000000
D   0.714883  -0.369965   0.108245   0.108638  -1.387713
E   0.760233   2.558522   0.580643   0.440865   0.489467
F   0.139767  -0.282094   0.331522  -0.684318  -0.297040

In [29]:
new_columns = ['col1', 'col2', 'col3','col4', 'col5', 'col6']

In [30]:
dframe.reindex(columns = new_columns)

col1      col2      col3      col4      col5  col6
A -0.970725 -1.100634 -1.796524  0.351451 -2.192120   NaN
B -1.566977 -0.675692  0.472938 -0.287232 -1.809274   NaN
D  0.714883 -0.369965  0.108245  0.108638 -1.387713   NaN
E  0.760233  2.558522  0.580643  0.440865  0.489467   NaN
F  0.139767 -0.282094  0.331522 -0.684318 -0.297040   NaN

In [33]:
dframe

new_rows = ['A','B','C','D','E','F']

In [34]:
dframe.ix[new_rows,new_columns]

col1      col2      col3      col4      col5  col6
A -0.970725 -1.100634 -1.796524  0.351451 -2.192120   NaN
B -1.566977 -0.675692  0.472938 -0.287232 -1.809274   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D  0.714883 -0.369965  0.108245  0.108638 -1.387713   NaN
E  0.760233  2.558522  0.580643  0.440865  0.489467   NaN
F  0.139767 -0.282094  0.331522 -0.684318 -0.297040   NaN